spring:
      application:
          name: spring-boot-webflux
      data:
          mongodb:
                  uri: mongodb://localhost:27017/test
      thymeleaf:
        reactive:
          max-chunk-size: 1024
          chunked-mode-view-names: list-chunked

config:
      uploads:
          path: "C://SpringWebFlux//uploads//"