spring:
  application:
    name: spring-boot-webflux-products

server:
  port: 8001

  data:
    mongodb:
      uri: mongodb://localhost:27017/test

config:
  uploads:
    path: "C://SpringWebFlux//uploads//"
  base:
    uri: "/api/v2/products"
